 
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AmapContainer: typeof import('./src/components/Amaps/AmapContainer.vue')['default']
    LineChart: typeof import('./src/components/Charts/lineChart.vue')['default']
    OverView: typeof import('./src/components/Charts/OverView.vue')['default']
    ReDialog: typeof import('./src/components/ReDialog/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Src: typeof import('./src/components/ReText/src/index.vue')['default']
    TableChart: typeof import('./src/components/Charts/TableChart.vue')['default']
  }
}
